version: '3.1' # specify docker-compose version
services: 
  proxy:
    container_name: proxy
    build: 'proxy'
    ports: 
     - "8080:80"
    #  - 443:443
    # links:
    #   - admin

  admin:
    container_name: admin
    build: 'AdminService'
    environment:
      - NODE_ENV=docker
    ports:
      - "9002:9002"
    links:
      - mongo

  user:
    container_name: user-service
    build: 'UserService'
    environment:
      - NODE_ENV=docker
    ports:
      - "9005:9005"
    links:
      - mongo
    

  mongo: 
    container_name: DB
    image: mongo
    volumes:
    - db-data:/usr/src/mongo
    expose:
    - "27017" # specify port forwarding

volumes:
  db-data: